config/routes.rb
Rails.application.routes.draw do
  resources :sounds
  root 'sounds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sound.rb
class Sound < ApplicationRecord
  mount_uploader :audio, AudioUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  def index
    @sounds = Sound.all
  end

  def new
    @sound = Sound.new
  end

  def create
    @sound = Sound.new(sound_params)
    if @sound.save
      redirect_to sounds_path, notice: 'Sound was successfully added.'
    else
      render :new
    end
  end

  private

  def sound_params
    params.require(:sound).permit(:name, :audio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soundboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sounds/index.html.erb
<h1>Soundboard</h1>

<%= link_to 'Add Sound', new_sound_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Audio</th>
    </tr>
  </thead>
  <tbody>
    <% @sounds.each do |sound| %>
      <tr>
        <td><%= sound.name %></td>
        <td><%= audio_tag sound.audio_url, controls: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sounds/new.html.erb
<h1>Add Sound</h1>

<%= form_with(model: @sound, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :audio %>
    <%= form.file_field :audio, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Sound', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', sounds_path, class: 'btn btn-secondary' %>